pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=build (10.x)"
      - "check-success=build (12.x)"
      - "check-success=build (14.x)"
      - "check-success=build (3.9)"
      - "check-success=build (3.8)"
      - "check-success=build (3.9)"
    actions:
      merge:
        method: squash
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "check-success=build (10.x)"
      - "check-success=build (12.x)"
      - "check-success=build (14.x)"
      - "check-success=build (3.9)"
      - "check-success=build (3.8)"
      - "check-success=build (3.9)"
    actions:
      merge:
        method: squash