pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=CI-Construct
      - check-success=CI-Lambda
    actions:
      merge:
        method: squash
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=CI-Construct
      - check-success=CI-Lambda
    actions:
      merge:
        method: merge