name: CI-Lambda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install pipenv
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - run: find . -type f
    - run: pipenv lock -r --dev >requirements.txt
    - run: find . -type f
    - run: cat requirements.txt
    - run: pip install -r requirements.txt
    - run: docker pull localstack/localstack:latest
    - run: localstack start 2>/dev/null & sleep 5
    - run: coverage run --source . -m unittest discover
    - run: coverage report --show-missing